Vagrant.configure("2") do |config|
  
  config.vm.box = "techchad2022/ubuntu2204"
  config.vm.hostname = "app.local"
  config.vm.network "public_network", 
    ip: "192.168.0.17",
    bridge: "wlp2s0"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker-for-python-app"
    vb.memory = "2048"
    vb.cpus = 2
  end
  
  config.vm.provision "docker"
  # config.vm.provision "shell", path: "kind-install.sh"
end