Vagrant.configure("2") do |config|
  
  config.vm.box = "techchad2022/ubuntu2204"
  config.vm.hostname = "kind"
  config.vm.network "public_network", 
    use_dhcp_assigned_default_route: true,
    bridge: "wlp2s0"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "kind-cluster"
    vb.memory = "2048"
    vb.cpus = 2
  end
  
  config.vm.provision "docker"
  # config.vm.provision "shell", path: "kind-install.sh"
end